const college = {
    "am-ET": "Artificial Intelligent",
    "ar-SA": "Mechatronics",
    "be-BY": "Mechanical Engineering",
    "bem-ZM": "Civil",
    "bi-VU": "Naturopathy",
    "bjs-BB": "Automobile",
    "bn-IN": "CSE",
    "bo-CN": "IT",
    "br-FR": "BSC-CSD",
    "bs-BA": "BSC-IT",
    "ca-ES": "BSC-SS",
    "cop-EG": "ECE",
    "cs-CZ": "EEE",
    "cy-GB": "EIE",
    "da-DK": "FOOD-TECH",
    "dz-BT": "CHEMICAL",
    "de-DE": "MSC",
    "dv-MV": "MBA",
    "el-GR": "MCA",
    
}